
import javax.swing.ImageIcon;
import javax.swing.JFrame;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class startLogin extends javax.swing.JFrame {

    /**
     * Creates new form startLogin
     */
    studentLogin studentlogin;
    teacherLogin teacherlogin;
    
    public startLogin() {
        
        initComponents();
        setSize(650, 550);
        setLocationRelativeTo(null);
        ImageIcon normalright = new ImageIcon(getClass().getResource("/AppBackground/student-normal.png"));
        studentLabel.setIcon(normalright);
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/AppBackground/teacher-normal.png"));
        teacherLabel.setIcon(normalleft);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teacherLabel = new javax.swing.JLabel();
        studentLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(null);

        teacherLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                teacherLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                teacherLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                teacherLabelMousePressed(evt);
            }
        });
        getContentPane().add(teacherLabel);
        teacherLabel.setBounds(79, 164, 176, 165);

        studentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                studentLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                studentLabelMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                studentLabelMousePressed(evt);
            }
        });
        getContentPane().add(studentLabel);
        studentLabel.setBounds(385, 164, 165, 165);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/loginbackground.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 650, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void teacherLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseClicked
            ImageIcon click = new ImageIcon(getClass().getResource("/AppBackground/teacher-click.png"));
            teacherLabel.setIcon(click);
            teacherlogin = new teacherLogin();
            setVisible(false);
            teacherlogin.setVisible(true);
    }//GEN-LAST:event_teacherLabelMouseClicked

    private void studentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseClicked
            ImageIcon clicked = new ImageIcon(getClass().getResource("/AppBackground/student-click.png"));
            studentLabel.setIcon(clicked);
            studentlogin = new studentLogin();
            setVisible(false);
            studentlogin.setVisible(true);
    }//GEN-LAST:event_studentLabelMouseClicked

    private void studentLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseEntered
            ImageIcon hover = new ImageIcon(getClass().getResource("/AppBackground/student-hover.png"));
            studentLabel.setIcon(hover);
    }//GEN-LAST:event_studentLabelMouseEntered

    private void studentLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseExited
            ImageIcon normal = new ImageIcon(getClass().getResource("/AppBackground/student-normal.png"));
            studentLabel.setIcon(normal);
    }//GEN-LAST:event_studentLabelMouseExited

    private void studentLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMousePressed
            ImageIcon clicked = new ImageIcon(getClass().getResource("/AppBackground/student-click.png"));
            studentLabel.setIcon(clicked);
    }//GEN-LAST:event_studentLabelMousePressed

    private void teacherLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseEntered
            ImageIcon hover = new ImageIcon(getClass().getResource("/AppBackground/teacher-hover.png"));
            teacherLabel.setIcon(hover);
    }//GEN-LAST:event_teacherLabelMouseEntered

    private void teacherLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseExited
            ImageIcon normal = new ImageIcon(getClass().getResource("/AppBackground/teacher-normal.png"));
            teacherLabel.setIcon(normal);
    }//GEN-LAST:event_teacherLabelMouseExited

    private void teacherLabelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMousePressed
            ImageIcon click = new ImageIcon(getClass().getResource("/AppBackground/teacher-click.png"));
            teacherLabel.setIcon(click);
    }//GEN-LAST:event_teacherLabelMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(startLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(startLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(startLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(startLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() 
        {    
            public void run() {
                try{
                    Thread.sleep(100);
                    
                }catch(Exception e){
                    
                }finally{
                    new startLogin().setVisible(true);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JLabel teacherLabel;
    // End of variables declaration//GEN-END:variables
}
