
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class studentStuff extends javax.swing.JFrame {

    /**
     * Creates new form studentStuff
     */
    studentNotice studentnotice;
    studentTimeTable studenttimetable;
    studentMentorFeedback studentmentorFeedback;
    studentUpcomingEvents studentupcomingEvents;
    studentLogin studentlogin;
    studentStuff studentstuff;
    String userName;
    String password;
    Boolean logged = false;
    public studentStuff() {
        initComponents();
        setSize(875,550);
        setLocationRelativeTo(null);
        setBackground(Color.white);
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
    }
    
    public studentStuff(String userName, String password, Boolean logged) {
        initComponents();
        setSize(875, 550);
        setLocationRelativeTo(null);
        setBackground(Color.white);
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
        if(logged == true){
            homeState.setText("Hello "+userName);
             this.userName = userName;
             this.password = password;
             this.logged = logged;
        }else{
            System.out.println("my bad");
        }
    } 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabsPanelParent = new javax.swing.JPanel();
        miniPanel = new javax.swing.JPanel();
        noticeLabel = new javax.swing.JLabel();
        timeTablelabel = new javax.swing.JLabel();
        mentorFeedbackLabel = new javax.swing.JLabel();
        upcomingEventsLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        menuPanelParent = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        studentImage = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        homeState = new javax.swing.JLabel();
        academicsState = new javax.swing.JLabel();
        logOutLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setBackground(new java.awt.Color(254, 254, 254));
        setForeground(java.awt.Color.white);
        setPreferredSize(new java.awt.Dimension(860, 550));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 500));

        tabsPanelParent.setBackground(new java.awt.Color(255, 255, 255));

        miniPanel.setBackground(new java.awt.Color(255, 255, 255));
        miniPanel.setOpaque(false);
        miniPanel.setLayout(null);

        noticeLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        noticeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        noticeLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/notice.png"))); // NOI18N
        noticeLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        noticeLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noticeLabelMouseClicked(evt);
            }
        });
        miniPanel.add(noticeLabel);
        noticeLabel.setBounds(18, 34, 527, 100);

        timeTablelabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        timeTablelabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        timeTablelabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/timetable.png"))); // NOI18N
        timeTablelabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        timeTablelabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                timeTablelabelMouseClicked(evt);
            }
        });
        miniPanel.add(timeTablelabel);
        timeTablelabel.setBounds(10, 150, 527, 100);

        mentorFeedbackLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        mentorFeedbackLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        mentorFeedbackLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/feedback.png"))); // NOI18N
        mentorFeedbackLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        mentorFeedbackLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mentorFeedbackLabelMouseClicked(evt);
            }
        });
        miniPanel.add(mentorFeedbackLabel);
        mentorFeedbackLabel.setBounds(10, 260, 527, 100);

        upcomingEventsLabel.setFont(new java.awt.Font("Calibri Light", 0, 18)); // NOI18N
        upcomingEventsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        upcomingEventsLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/upcoming.png"))); // NOI18N
        upcomingEventsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        upcomingEventsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcomingEventsLabelMouseClicked(evt);
            }
        });
        miniPanel.add(upcomingEventsLabel);
        upcomingEventsLabel.setBounds(10, 370, 520, 100);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Welcome back, Student!.png"))); // NOI18N
        miniPanel.add(jLabel1);
        jLabel1.setBounds(0, 0, 350, 28);

        javax.swing.GroupLayout tabsPanelParentLayout = new javax.swing.GroupLayout(tabsPanelParent);
        tabsPanelParent.setLayout(tabsPanelParentLayout);
        tabsPanelParentLayout.setHorizontalGroup(
            tabsPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabsPanelParentLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(miniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        tabsPanelParentLayout.setVerticalGroup(
            tabsPanelParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabsPanelParentLayout.createSequentialGroup()
                .addComponent(miniPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        menuPanelParent.setOpaque(false);
        menuPanelParent.setPreferredSize(new java.awt.Dimension(238, 478));
        menuPanelParent.setLayout(null);

        iconPanel.setPreferredSize(new java.awt.Dimension(218, 180));
        iconPanel.setLayout(null);

        studentImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/student.png"))); // NOI18N
        iconPanel.add(studentImage);
        studentImage.setBounds(60, 0, 170, 210);

        menuPanelParent.add(iconPanel);
        iconPanel.setBounds(0, 31, 244, 214);

        menuPanel.setPreferredSize(new java.awt.Dimension(218, 244));

        homeState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeStateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeStateMouseExited(evt);
            }
        });

        academicsState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                academicsStateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                academicsStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                academicsStateMouseExited(evt);
            }
        });

        logOutLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        logOutLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logOutLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/log out.png"))); // NOI18N
        logOutLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutLabelMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/Rectangle 9.png"))); // NOI18N

        javax.swing.GroupLayout menuPanelLayout = new javax.swing.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeState, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(academicsState, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, Short.MAX_VALUE))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(homeState, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(logOutLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, menuPanelLayout.createSequentialGroup()
                    .addContainerGap(88, Short.MAX_VALUE)
                    .addComponent(academicsState, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(111, Short.MAX_VALUE)))
            .addGroup(menuPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 244, Short.MAX_VALUE))
        );

        menuPanelParent.add(menuPanel);
        menuPanel.setBounds(0, 263, 244, 244);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        menuPanelParent.add(jLabel3);
        jLabel3.setBounds(0, 0, 250, 510);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(menuPanelParent, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tabsPanelParent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(580, 580, 580))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(menuPanelParent, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(32, Short.MAX_VALUE))
                    .addComponent(tabsPanelParent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 0, 830, 540);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noticeLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noticeLabelMouseClicked
        studentnotice = new studentNotice(userName, password, logged);
        setVisible(false);
        studentnotice.setVisible(true);
    }//GEN-LAST:event_noticeLabelMouseClicked

    private void timeTablelabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_timeTablelabelMouseClicked
        studenttimetable = new studentTimeTable(userName, password, logged);
        setVisible(false);
        studenttimetable.setVisible(true);
    }//GEN-LAST:event_timeTablelabelMouseClicked

    private void mentorFeedbackLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mentorFeedbackLabelMouseClicked
        studentmentorFeedback = new studentMentorFeedback(userName, password, logged);
        setVisible(false);
        studentmentorFeedback.setVisible(true);
    }//GEN-LAST:event_mentorFeedbackLabelMouseClicked

    private void upcomingEventsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcomingEventsLabelMouseClicked
        studentupcomingEvents = new studentUpcomingEvents(userName, password, logged);
        setVisible(false);
        studentupcomingEvents.setVisible(true);
    }//GEN-LAST:event_upcomingEventsLabelMouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.white);
    }//GEN-LAST:event_formWindowOpened

    private void homeStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseClicked
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/home button click.png"));
        homeState.setIcon(click);
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_homeStateMouseClicked

    private void academicsStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseClicked
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/academics_click.png"));
        academicsState.setIcon(click);
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_academicsStateMouseClicked

    private void homeStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseEntered
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/home button click.png"));
        homeState.setIcon(click);
    }//GEN-LAST:event_homeStateMouseEntered

    private void academicsStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseEntered
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/academics_click.png"));
        academicsState.setIcon(click);
    }//GEN-LAST:event_academicsStateMouseEntered

    private void homeStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseExited
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
    }//GEN-LAST:event_homeStateMouseExited

    private void academicsStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseExited
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
    }//GEN-LAST:event_academicsStateMouseExited

    private void logOutLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutLabelMouseClicked
        studentlogin = new studentLogin(userName, password, logged);
        setVisible(false);
        studentlogin.setVisible(true);
    }//GEN-LAST:event_logOutLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentStuff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentStuff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicsState;
    private javax.swing.JLabel homeState;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel logOutLabel;
    private javax.swing.JLabel mentorFeedbackLabel;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel menuPanelParent;
    private javax.swing.JPanel miniPanel;
    private javax.swing.JLabel noticeLabel;
    private javax.swing.JLabel studentImage;
    private javax.swing.JPanel tabsPanelParent;
    private javax.swing.JLabel timeTablelabel;
    private javax.swing.JLabel upcomingEventsLabel;
    // End of variables declaration//GEN-END:variables
}
