/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class studentUpcomingEvents extends javax.swing.JFrame {

    /**
     * Creates new form studentUpcomingEvents
     */
    studentStuff studentstuff;
    connectionClass sql;
    int baseNumber=0;
    String userName;
    String password;
    Boolean logged = false;
    
    public studentUpcomingEvents() {
        initComponents();
        setSize(860, 550);
        setLocationRelativeTo(null);
        sql=new connectionClass();
        String query="SELECT * FROM eventCalendar";
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                baseNumber=sql.resultSet.getInt("serialNo.");
            }
        }catch(Exception e){
            
        }
    }
    public studentUpcomingEvents(String userName, String password, Boolean logged) {
        initComponents();
        setSize(860, 550);
        setLocationRelativeTo(null);
        sql=new connectionClass();
        this.userName = userName;
        this.password = password;
        this.logged = logged;
        String query="SELECT * FROM eventCalendar";
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                baseNumber=sql.resultSet.getInt("serialNo.");
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        event_4 = new javax.swing.JLabel();
        event_2 = new javax.swing.JLabel();
        event_5 = new javax.swing.JLabel();
        event_3 = new javax.swing.JLabel();
        event_1 = new javax.swing.JLabel();
        event_1_label = new javax.swing.JLabel();
        event_2_label = new javax.swing.JLabel();
        event_3_label = new javax.swing.JLabel();
        event_4_label = new javax.swing.JLabel();
        event_5_label = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setMaximumSize(new java.awt.Dimension(650, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        parentPanel.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                parentPanelAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        parentPanel.setLayout(null);

        event_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        event_4.setForeground(new java.awt.Color(153, 153, 153));
        parentPanel.add(event_4);
        event_4.setBounds(60, 281, 510, 45);

        event_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        event_2.setForeground(new java.awt.Color(153, 153, 153));
        parentPanel.add(event_2);
        event_2.setBounds(60, 101, 510, 45);

        event_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        event_5.setForeground(new java.awt.Color(153, 153, 153));
        parentPanel.add(event_5);
        event_5.setBounds(60, 371, 510, 45);

        event_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        event_3.setForeground(new java.awt.Color(153, 153, 153));
        parentPanel.add(event_3);
        event_3.setBounds(60, 191, 510, 45);

        event_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        event_1.setForeground(new java.awt.Color(153, 153, 153));
        parentPanel.add(event_1);
        event_1.setBounds(60, 10, 510, 45);

        event_1_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentPanel.add(event_1_label);
        event_1_label.setBounds(50, 0, 530, 60);

        event_2_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentPanel.add(event_2_label);
        event_2_label.setBounds(50, 90, 530, 60);

        event_3_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentPanel.add(event_3_label);
        event_3_label.setBounds(50, 180, 530, 60);

        event_4_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentPanel.add(event_4_label);
        event_4_label.setBounds(50, 270, 530, 60);

        event_5_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentPanel.add(event_5_label);
        event_5_label.setBounds(50, 360, 530, 60);

        getContentPane().add(parentPanel);
        parentPanel.setBounds(130, 60, 610, 460);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 11, 16, 16);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Welcome back, Student!.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(130, 10, 420, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 550);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 60, 610, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parentPanelAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_parentPanelAncestorAdded
        String query="SELECT * FROM eventCalendar";
        //System.out.println("it came here");
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            //System.out.println("it came here");
            while(sql.resultSet.next()){
                //System.out.println("it came here");
                if(sql.resultSet.getInt("serialNo.")==baseNumber){
                    event_1.setText("        "+sql.resultSet.getString("eventName"));
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-1){
                    event_2.setText("        "+sql.resultSet.getString("eventName"));
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-2){
                    event_3.setText("        "+sql.resultSet.getString("eventName"));
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-3){
                    event_4.setText("        "+sql.resultSet.getString("eventName"));
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-4){
                    event_5.setText("        "+sql.resultSet.getString("eventName"));
                }
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_parentPanelAncestorAdded

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentUpcomingEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentUpcomingEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentUpcomingEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentUpcomingEvents.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentUpcomingEvents().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel event_1;
    private javax.swing.JLabel event_1_label;
    private javax.swing.JLabel event_2;
    private javax.swing.JLabel event_2_label;
    private javax.swing.JLabel event_3;
    private javax.swing.JLabel event_3_label;
    private javax.swing.JLabel event_4;
    private javax.swing.JLabel event_4_label;
    private javax.swing.JLabel event_5;
    private javax.swing.JLabel event_5_label;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel parentPanel;
    // End of variables declaration//GEN-END:variables
}
