
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class studentNotice extends javax.swing.JFrame {

    /**
     * Creates new form studentNotice
     */
    studentStuff studentstuff;
    connectionClass sql;
    int baseNumber =0;
    FileOutputStream output=null;
    InputStream input=null;
    int number=0;
    String userName;
    String password;
    Boolean logged = false;
    
    public studentNotice() {
        initComponents();
        sql=new connectionClass();
        setSize(875, 550);
        setLocationRelativeTo(null);
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
        String query="SELECT * FROM noticePdf";
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                baseNumber=sql.resultSet.getInt("serialNo.");
            }
        }catch(Exception e){
            
        }
    }
    
    public studentNotice(String userName, String password, Boolean logged) {
        initComponents();
        sql=new connectionClass();
        setSize(875, 550);
        setLocationRelativeTo(null);
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
        this.userName = userName;
        this.password = password;
        this.logged = logged;
        String query="SELECT * FROM noticePdf";
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                baseNumber=sql.resultSet.getInt("serialNo.");
            }
        }catch(Exception e){
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentFrame = new javax.swing.JPanel();
        notice_1 = new javax.swing.JLabel();
        notice_2 = new javax.swing.JLabel();
        notice_3 = new javax.swing.JLabel();
        notice_4 = new javax.swing.JLabel();
        notice_5 = new javax.swing.JLabel();
        notice_1_label = new javax.swing.JLabel();
        notice_2_label = new javax.swing.JLabel();
        notice_3_label = new javax.swing.JLabel();
        notice_4_label = new javax.swing.JLabel();
        notice_5_label = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        iconPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        menuPanel = new javax.swing.JPanel();
        homeState = new javax.swing.JLabel();
        academicsState = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setPreferredSize(new java.awt.Dimension(875, 550));
        getContentPane().setLayout(null);

        parentFrame.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                parentFrameAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        parentFrame.setLayout(null);

        notice_1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notice_1.setForeground(new java.awt.Color(153, 153, 153));
        notice_1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_1MouseClicked(evt);
            }
        });
        parentFrame.add(notice_1);
        notice_1.setBounds(70, 30, 428, 40);

        notice_2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notice_2.setForeground(new java.awt.Color(153, 153, 153));
        notice_2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_2MouseClicked(evt);
            }
        });
        parentFrame.add(notice_2);
        notice_2.setBounds(67, 109, 428, 40);

        notice_3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notice_3.setForeground(new java.awt.Color(153, 153, 153));
        notice_3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_3MouseClicked(evt);
            }
        });
        parentFrame.add(notice_3);
        notice_3.setBounds(70, 180, 428, 40);

        notice_4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notice_4.setForeground(new java.awt.Color(153, 153, 153));
        notice_4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_4MouseClicked(evt);
            }
        });
        parentFrame.add(notice_4);
        notice_4.setBounds(67, 250, 428, 40);

        notice_5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        notice_5.setForeground(new java.awt.Color(153, 153, 153));
        notice_5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                notice_5MouseClicked(evt);
            }
        });
        parentFrame.add(notice_5);
        notice_5.setBounds(67, 326, 428, 40);

        notice_1_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentFrame.add(notice_1_label);
        notice_1_label.setBounds(60, 30, 440, 40);

        notice_2_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentFrame.add(notice_2_label);
        notice_2_label.setBounds(60, 110, 440, 40);

        notice_3_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentFrame.add(notice_3_label);
        notice_3_label.setBounds(60, 180, 440, 40);

        notice_4_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentFrame.add(notice_4_label);
        notice_4_label.setBounds(60, 250, 440, 40);

        notice_5_label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/notice rect.png"))); // NOI18N
        parentFrame.add(notice_5_label);
        notice_5_label.setBounds(60, 320, 440, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        parentFrame.add(jLabel3);
        jLabel3.setBounds(0, 0, 530, 410);

        getContentPane().add(parentFrame);
        parentFrame.setBounds(300, 60, 530, 410);

        jPanel1.setLayout(null);

        iconPanel.setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/student.png"))); // NOI18N
        iconPanel.add(jLabel4);
        jLabel4.setBounds(60, 0, 160, 170);

        jPanel1.add(iconPanel);
        iconPanel.setBounds(10, 11, 230, 170);

        menuPanel.setLayout(null);

        homeState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeStateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeStateMouseExited(evt);
            }
        });
        menuPanel.add(homeState);
        homeState.setBounds(0, 30, 250, 45);

        academicsState.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                academicsStateMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                academicsStateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                academicsStateMouseExited(evt);
            }
        });
        menuPanel.add(academicsState);
        academicsState.setBounds(0, 90, 250, 45);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/Rectangle 9.png"))); // NOI18N
        menuPanel.add(jLabel5);
        jLabel5.setBounds(0, 0, 250, 250);

        jPanel1.add(menuPanel);
        menuPanel.setBounds(0, 197, 250, 250);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 250, 500);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(18, 11, 16, 16);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Welcome back, Student!.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(350, 10, 360, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 250, 500);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void parentFrameAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_parentFrameAncestorAdded
        String query="SELECT * FROM noticePdf";
        //System.out.println("it came here");
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            //System.out.println("it came here");
            while(sql.resultSet.next()){
                //System.out.println("it came here");
                if(sql.resultSet.getInt("serialNo.")==baseNumber){
                    notice_1.setText(" "+sql.resultSet.getString("noticeNumber"));
                    
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-1){
                    notice_2.setText(" "+sql.resultSet.getString("noticeNumber"));
                    
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-2){
                    notice_3.setText(" "+sql.resultSet.getString("noticeNumber"));
                    
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-3){
                    notice_4.setText(" "+sql.resultSet.getString("noticeNumber"));
                    
                }
                if(sql.resultSet.getInt("serialNo.")==baseNumber-4){
                    notice_5.setText(" "+sql.resultSet.getString("noticeNumber"));
                    
                }
//                if(sql.resultSet.getInt("serialNo.")==baseNumber-5){
//                    notice_6.setText(" "+sql.resultSet.getString("noticeNumber"));
//                    
//                }
//                if(sql.resultSet.getInt("serialNo.")==baseNumber-6){
//                    notice_7.setText(" "+sql.resultSet.getString("noticeNumber"));
//                    
//                }
//                if(sql.resultSet.getInt("serialNo.")==baseNumber-7){
//                    notice_8.setText(" "+sql.resultSet.getString("noticeNumber"));
//                    
//                }
//                if(sql.resultSet.getInt("serialNo.")==baseNumber-8){
//                    notice_9.setText(" "+sql.resultSet.getString("noticeNumber"));
//                    
//                }
            }
            
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_parentFrameAncestorAdded

    private void notice_1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_1MouseClicked
        try {
            number=1;
            getPDF();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_notice_1MouseClicked

    private void notice_2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_2MouseClicked
        try {
            number=2;
            getPDF();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_notice_2MouseClicked

    private void notice_3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_3MouseClicked
        try {
            number=3;
            getPDF();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_notice_3MouseClicked

    private void notice_4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_4MouseClicked
        try {
            number=4;
            getPDF();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_notice_4MouseClicked

    private void notice_5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notice_5MouseClicked
        try {
            number=5;
            getPDF();
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_notice_5MouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void homeStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseClicked
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/home button click.png"));
        homeState.setIcon(click);
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_homeStateMouseClicked

    private void homeStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseEntered
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/home button click.png"));
        homeState.setIcon(click);
    }//GEN-LAST:event_homeStateMouseEntered

    private void homeStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeStateMouseExited
        ImageIcon normalright = new ImageIcon(getClass().getResource("/Icons/home button normal.png"));
        homeState.setIcon(normalright);
    }//GEN-LAST:event_homeStateMouseExited

    private void academicsStateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseClicked
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/academics_click.png"));
        academicsState.setIcon(click);
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_academicsStateMouseClicked

    private void academicsStateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseEntered
        ImageIcon click = new ImageIcon(getClass().getResource("/Icons/academics_click.png"));
        academicsState.setIcon(click);
    }//GEN-LAST:event_academicsStateMouseEntered

    private void academicsStateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_academicsStateMouseExited
        ImageIcon normalleft = new ImageIcon(getClass().getResource("/Icons/academics_normal.png"));
        academicsState.setIcon(normalleft);
    }//GEN-LAST:event_academicsStateMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentNotice.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentNotice().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academicsState;
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel homeState;
    private javax.swing.JPanel iconPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel notice_1;
    private javax.swing.JLabel notice_1_label;
    private javax.swing.JLabel notice_2;
    private javax.swing.JLabel notice_2_label;
    private javax.swing.JLabel notice_3;
    private javax.swing.JLabel notice_3_label;
    private javax.swing.JLabel notice_4;
    private javax.swing.JLabel notice_4_label;
    private javax.swing.JLabel notice_5;
    private javax.swing.JLabel notice_5_label;
    private javax.swing.JPanel parentFrame;
    // End of variables declaration//GEN-END:variables

    private void getPDF() throws IOException {
        String fileName=null;
        String noticeNum;
        String query=null;
        switch(number){
            case 1:
                fileName=notice_1.getText().trim();
                noticeNum="'"+fileName+"'";
                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
                break;
              
            case 2:
                fileName=notice_2.getText().trim();
                noticeNum="'"+fileName+"'";
                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
                break;
                
            case 3:
                fileName=notice_3.getText().trim();
                noticeNum="'"+fileName+"'";
                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
                break;
                
            case 4:
                fileName=notice_4.getText().trim();
                noticeNum="'"+fileName+"'";
                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
                break;
            
            case 5:
                fileName=notice_5.getText().trim();
                noticeNum="'"+fileName+"'";
                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
                break;
               
//            case 6:
//                fileName=notice_6.getText().trim();
//                noticeNum="'"+fileName+"'";
//                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
//                break;    
//               
//            case 7:
//                fileName=notice_7.getText().trim();
//                noticeNum="'"+fileName+"'";
//                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
//                break;
//               
//            case 8:
//                fileName=notice_8.getText().trim();
//                noticeNum="'"+fileName+"'";
//                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
//                break;
//            
//            case 9:
//                fileName=notice_9.getText().trim();
//                noticeNum="'"+fileName+"'";
//                query="SELECT PDF FROM noticePdf WHERE noticeNumber="+noticeNum;
//                break;
                
            default:
                break;
            
        }
        //System.out.println(query);
            //String query="SELECT PDF FROM noticePdf WHERE noticeNumber='notice1649'";
            try{
                sql.resultSet=sql.statement.executeQuery(query);
                File newFile=new File("C:\\Users\\Anant Kumar Mishra\\Downloads\\"+fileName+".pdf");
                output=new FileOutputStream(newFile);          
                if(sql.resultSet.next()){
                    input=sql.resultSet.getBinaryStream("PDF");
                    //System.out.println("hello");
                    byte[] buffer=new byte[10000];
                    while(input.read(buffer)>0){
                        output.write(buffer);
                    }
                    //System.out.println(newFile.getAbsolutePath());
            }
            }catch(Exception e){
                System.out.println(e);
            }finally{
                if(input!=null){
                    input.close();
                }
                if(output!=null){
                    output.close();
                }
            }
            
    }
}
