
import java.awt.Color;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class studentMentorFeedback extends javax.swing.JFrame {

    /**
     * Creates new form studentMentorFeedback
     */
    studentStuff studentstuff;
    String userName;
    String password;
    Boolean logged = false;
    int departmentComboSelection = 0;
    
    public studentMentorFeedback() {
        initComponents();
        setSize(860, 550);
        setLocationRelativeTo(null);
    }
    
    public studentMentorFeedback(String userName, String password, Boolean logged) {
        initComponents();
        setSize(860, 550);
        setLocationRelativeTo(null);
        this.userName = userName;
        this.password = password;
        this.logged = logged;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        teachingGroup = new javax.swing.ButtonGroup();
        backButton = new javax.swing.JLabel();
        parentPanel = new javax.swing.JPanel();
        menuPanel = new javax.swing.JPanel();
        sessionName = new javax.swing.JLabel();
        departmentName = new javax.swing.JLabel();
        teacherName = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        sessionCombo = new javax.swing.JComboBox<>();
        departmentCombo = new javax.swing.JComboBox<>();
        teacherNameCombo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setMaximumSize(new java.awt.Dimension(650, 550));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 11, 16, 16);

        parentPanel.setBackground(new java.awt.Color(255, 255, 255));
        parentPanel.setLayout(null);

        menuPanel.setBackground(getBackground());
        menuPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 128, 46), 1, true));
        menuPanel.setLayout(null);

        sessionName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sessionName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        sessionName.setText("SESSION");
        menuPanel.add(sessionName);
        sessionName.setBounds(11, 12, 109, 25);

        departmentName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        departmentName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        departmentName.setText("DEPARTMENT");
        menuPanel.add(departmentName);
        departmentName.setBounds(593, 12, 86, 25);

        teacherName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        teacherName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        teacherName.setText("TEACHER'S NAME");
        menuPanel.add(teacherName);
        teacherName.setBounds(261, 12, 109, 25);

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        menuPanel.add(submitButton);
        submitButton.setBounds(262, 57, 69, 23);

        clearButton.setText("CLEAR");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        menuPanel.add(clearButton);
        clearButton.setBounds(494, 57, 65, 23);

        sessionCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        sessionCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2015-16", "2016-17", "2017-18" }));
        menuPanel.add(sessionCombo);
        sessionCombo.setBounds(130, 16, 100, 21);

        departmentCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        departmentCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Mechanical Engg.", "Electrical Engg.", "Civil Engg.", "Electronics & Electrical Engg.", "Electronics & Telecommunication Engg.", "Electronics & Instrumentation Engg.", "Computer Science Engg.", "Information Technology Engg." }));
        departmentCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                departmentComboActionPerformed(evt);
            }
        });
        menuPanel.add(departmentCombo);
        departmentCombo.setBounds(689, 16, 120, 21);

        teacherNameCombo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        teacherNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Department First" }));
        menuPanel.add(teacherNameCombo);
        teacherNameCombo.setBounds(380, 14, 150, 25);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        menuPanel.add(jLabel3);
        jLabel3.setBounds(0, 0, 820, 110);

        parentPanel.add(menuPanel);
        menuPanel.setBounds(10, 11, 820, 110);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 128, 46), 1, true));

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jLabel1.setText("TEACHING");

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 255));
        teachingGroup.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton1.setText("Very Poor");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 255));
        teachingGroup.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton2.setText("Average");

        jRadioButton3.setBackground(new java.awt.Color(255, 255, 255));
        teachingGroup.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton3.setText("Good");

        jRadioButton4.setBackground(new java.awt.Color(255, 255, 255));
        teachingGroup.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton4.setText("Very Good");

        jRadioButton5.setBackground(new java.awt.Color(255, 255, 255));
        teachingGroup.add(jRadioButton5);
        jRadioButton5.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jRadioButton5.setText("Excellent");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jRadioButton1)
                .addGap(65, 65, 65)
                .addComponent(jRadioButton2)
                .addGap(65, 65, 65)
                .addComponent(jRadioButton3)
                .addGap(65, 65, 65)
                .addComponent(jRadioButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jRadioButton5)
                .addGap(43, 43, 43))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jRadioButton3)
                    .addComponent(jRadioButton4)
                    .addComponent(jRadioButton5))
                .addContainerGap())
        );

        parentPanel.add(jPanel1);
        jPanel1.setBounds(10, 132, 820, 95);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        parentPanel.add(jLabel2);
        jLabel2.setBounds(-10, -40, 860, 550);

        getContentPane().add(parentPanel);
        parentPanel.setBounds(10, 38, 840, 501);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Welcome back, Student!.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(80, 10, 450, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void departmentComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_departmentComboActionPerformed
        if(departmentCombo.getSelectedItem().equals("Mechanical Engg.")){
            Object[] mechTeachName={"Prof. Ashok K. Sahoo",
                "Prof. Raja Kishore Paramguru",
                "Prof. Lalit Kumar Pothal",
                "Prof. Saranjit Singh",
                "Prof. Bharat Chandra Routra",
                "Prof. Kunja Bihari Sahu",
                "Prof. Susanta Tripathy",
                "Prof. Purna Chandra Mishra"};
            departmentComboSelection = 1;
            teacherNameCombo.setModel(new DefaultComboBoxModel(mechTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Electrical Engg.")){
            Object[] elecTeachName={"Prof. Mayadhar Swain",
                "Prof. Chinmoy Kumar Panigrahi",
                "Dr. Prafulla Chandra Panda",
                "Prof. Himansu Sekhar Rauth",
                "Prof. Abhijit Dasgupta",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 2;
            teacherNameCombo.setModel(new DefaultComboBoxModel(elecTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Civil Engg.")){
            Object[] civilTeachName={"Prof. Benu Gopal Mohapatra",
                "Prof. Bitanjaya Das",
                "Prof. Bhagabat Jena",
                "Prof. Ashoke Kumar Rath",
                "Prof. Sanjib Moulick",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 2;
            teacherNameCombo.setModel(new DefaultComboBoxModel(civilTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Electronics & Electrical Engg.")){
            Object[] eeeTeachName={"Prof. Benu Gopal Mohapatra",
                "Prof. Bitanjaya Das",
                "Prof. Bhagabat Jena",
                "Prof. Ashoke Kumar Rath",
                "Prof. Sanjib Moulick",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 3;
            teacherNameCombo.setModel(new DefaultComboBoxModel(eeeTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Electronics & Telecommunication Engg.")){
            Object[] etcTeachName={"Prof. Arun Kumar Ray",
                "Prof. Asish Kumar Sen",
                "Prof. Shivcharan Lal Sharma",
                "Prof. Nirmal Kumar Rout",
                "Prof. Ghanshyam Rout",
                "Prof. Arindam Deb",
                "Prof. Prasant Kumar Patra",
                "Prof. Sarita Nanda"};
            departmentComboSelection = 4;
            teacherNameCombo.setModel(new DefaultComboBoxModel(etcTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Electrical & Instrumentation Engg.")){
            Object[] eiTeachName={"Prof. Benu Gopal Mohapatra",
                "Prof. Bitanjaya Das",
                "Prof. Bhagabat Jena",
                "Prof. Ashoke Kumar Rath",
                "Prof. Sanjib Moulick",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 5;
            teacherNameCombo.setModel(new DefaultComboBoxModel(eiTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Computer Science Engg.")){
            Object[] csTeachName={"Prof. Benu Gopal Mohapatra",
                "Prof. Bitanjaya Das",
                "Prof. Bhagabat Jena",
                "Prof. Ashoke Kumar Rath",
                "Prof. Sanjib Moulick",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 6;
            teacherNameCombo.setModel(new DefaultComboBoxModel(csTeachName));
        }
        if(departmentCombo.getSelectedItem().equals("Information Technology ENGG.")){
            Object[] itTeachName={"Prof. Benu Gopal Mohapatra",
                "Prof. Bitanjaya Das",
                "Prof. Bhagabat Jena",
                "Prof. Ashoke Kumar Rath",
                "Prof. Sanjib Moulick",
                "Prof. Ullash Kumar Rout",
                "Prof. Sarat Ch. Swain",
                "Prof. Manoj Kumar Maharana"};
            departmentComboSelection = 7;
            teacherNameCombo.setModel(new DefaultComboBoxModel(itTeachName));
        }
        
    }//GEN-LAST:event_departmentComboActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        
    }//GEN-LAST:event_submitButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        
    }//GEN-LAST:event_clearButtonActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        getContentPane().setBackground(Color.WHITE);
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentMentorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentMentorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentMentorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentMentorFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentMentorFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JButton clearButton;
    private javax.swing.JComboBox<String> departmentCombo;
    private javax.swing.JLabel departmentName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JComboBox<String> sessionCombo;
    private javax.swing.JLabel sessionName;
    private javax.swing.JButton submitButton;
    private javax.swing.JLabel teacherName;
    private javax.swing.JComboBox<String> teacherNameCombo;
    private javax.swing.ButtonGroup teachingGroup;
    // End of variables declaration//GEN-END:variables
}
