
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Anant Kumar Mishra
 */
public class studentTimeTable extends javax.swing.JFrame {

    /**
     * Creates new form studentTimeTable
     */
    studentStuff studentstuff;
    connectionClass sql;
    int branchSelection=0;
    String userName;
    String password;
    Boolean logged = false;
    
    public studentTimeTable() {
        initComponents();
        sql=new connectionClass();
        setSize(860, 550);
        setLocationRelativeTo(null);
    }
    public studentTimeTable(String userName, String password, Boolean logged) {
        initComponents();
        sql=new connectionClass();
        setSize(860, 550);
        setLocationRelativeTo(null);
        this.userName = userName;
        this.password = password;
        this.logged = logged;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        branchName = new javax.swing.JLabel();
        branchSelector = new javax.swing.JComboBox<>();
        semesterName = new javax.swing.JLabel();
        sectionName = new javax.swing.JLabel();
        sectionSelector = new javax.swing.JComboBox<>();
        semesterSelector = new javax.swing.JComboBox<>();
        submitButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        backButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setMaximumSize(new java.awt.Dimension(860, 550));
        setResizable(false);
        getContentPane().setLayout(null);

        branchName.setText("SELECT BRANCH");

        branchSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE ONE", "MECH ENG.", "AUTOMOBILE ENG.", "CIVIL ENG.", "ELECTRICAL ENG.", "ELECTRONICS & TELECOMM. ENG.", "ELECTRONICS & ELECTRICAL ENG.", "ELECTRICAL & INST. ENG.", "COMPUTER SCIENCE ENG.", "IT ENG." }));
        branchSelector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                branchSelectorActionPerformed(evt);
            }
        });

        semesterName.setText("SELECT SEMESTER");

        sectionName.setText("SELECT SECTION");

        sectionSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SELECT BRANCH FIRST" }));

        semesterSelector.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CHOOSE ONE", "SPRING", "AUTUMN" }));

        submitButton.setText("SUBMIT");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        clearButton.setText("CLEAR");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sectionName, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(branchName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(branchSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(semesterName))
                    .addComponent(sectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearButton)
                        .addContainerGap(150, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(semesterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(branchSelector)
                        .addComponent(semesterName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(semesterSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(branchName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sectionSelector, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearButton))
                .addGap(23, 23, 23))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(35, 35, 790, 100);

        table.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "TIME", "MONDAY", "TUESDAY", "WEDNESDAY", "THURSDAY", "FRIDAY", "SATURDAY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setMaximumSize(new java.awt.Dimension(525, 330));
        table.setPreferredSize(new java.awt.Dimension(525, 330));
        table.setRowHeight(30);
        table.setRowSelectionAllowed(false);
        table.getTableHeader().setResizingAllowed(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
            table.getColumnModel().getColumn(5).setResizable(false);
            table.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 766, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(35, 153, 790, 386);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 10, 16, 16);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/stuffbackground.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void branchSelectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_branchSelectorActionPerformed
       
        if(branchSelector.getSelectedItem().equals("MECH ENG.")){
            Object[] mechSec={"ME-1","ME-2","ME-3","ME-4","ME-5"};
            branchSelection=1;
            sectionSelector.setModel(new DefaultComboBoxModel(mechSec));
        }
        if(branchSelector.getSelectedItem().equals("AUTOMOBILE ENG.")){
            Object[] autoSec={"AE-1","AE-2","AE-3","AE-4","AE-5"};
            branchSelection=2;
            sectionSelector.setModel(new DefaultComboBoxModel(autoSec));
        }
        if(branchSelector.getSelectedItem().equals("CIVIL ENG.")){
            Object[] civilSec={"CE-1","CE-2","CE-3","CE-4","CE-5"};
            branchSelection=3;
            sectionSelector.setModel(new DefaultComboBoxModel(civilSec));
        }
        if(branchSelector.getSelectedItem().equals("ELECTRICAL ENG.")){
            Object[] elecSec={"EE-1","EE-2","EE-3","EE-4","EE-5"};
            branchSelection=4;
            sectionSelector.setModel(new DefaultComboBoxModel(elecSec)); 
        }
        if(branchSelector.getSelectedItem().equals("ELECTRONICS & TELECOMM. ENG.")){
            Object[] etcSec={"ETC-1","ETC-2","ETC-3","ETC-4","ETC-5"};
            branchSelection=5;
            sectionSelector.setModel(new DefaultComboBoxModel(etcSec));
        }
        if(branchSelector.getSelectedItem().equals("ELECTRONICS & ELECTRICAL ENG.")){
            Object[] eeeSec={"EEE-1","EEE-2","EEE-3","EEE-4","EEE-5"};
            branchSelection=6;
            sectionSelector.setModel(new DefaultComboBoxModel(eeeSec));
        }
        if(branchSelector.getSelectedItem().equals("ELECTRICAL & INST. ENG.")){
            Object[] eiSec={"E&I-1","E&I-2","E&I-3","E&I-4","E&I-5"};
            branchSelection=7;
            sectionSelector.setModel(new DefaultComboBoxModel(eiSec));
        }
        if(branchSelector.getSelectedItem().equals("COMPUTER SCIENCE ENG.")){
            Object[] cseSec={"CSE-1","CSE-2","CSE-3","CSE-4","CSE-5"};
            branchSelection=8;
            sectionSelector.setModel(new DefaultComboBoxModel(cseSec));
        }
        if(branchSelector.getSelectedItem().equals("IT ENG.")){
            Object[] itSec={"IT-1","IT-2","IT-3","IT-4","IT-5"};
            branchSelection=9;
            sectionSelector.setModel(new DefaultComboBoxModel(itSec));
        }
        
    }//GEN-LAST:event_branchSelectorActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        String query=null;
        switch (branchSelection) {
            case 1:
                if (sectionSelector.getSelectedItem().equals("ME-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ME-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ME-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ME-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ME-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM me5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 2:
                if (sectionSelector.getSelectedItem().equals("AE-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("AE-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("AE-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("AE-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("AE-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ae5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 3:
                if (sectionSelector.getSelectedItem().equals("CE-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CE-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CE-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CE-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CE-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ce5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 4:
                if (sectionSelector.getSelectedItem().equals("EE-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EE-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EE-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EE-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EE-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM ee5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 5:
                if (sectionSelector.getSelectedItem().equals("ETC-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ETC-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ETC-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ETC-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("ETC-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM etc5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 6:
                if (sectionSelector.getSelectedItem().equals("EEE-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EEE-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EEE-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EEE-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("EEE-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM eee5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 7:
                if (sectionSelector.getSelectedItem().equals("E&I-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("E&I-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("E&I-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("E&I-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("E&I-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM e&i5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 8:
                if (sectionSelector.getSelectedItem().equals("CSE-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CSE-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CSE-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CSE-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("CSE-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM cse5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            case 9:
                if (sectionSelector.getSelectedItem().equals("IT-1")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it1spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it1autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("IT-2")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it2spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it2autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("IT-3")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it3spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it3autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("IT-4")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it4spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it4autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else if (sectionSelector.getSelectedItem().equals("IT-5")) {
                    if (semesterSelector.getSelectedItem().equals("SPRING")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it5spring";
                    } else if (semesterSelector.getSelectedItem().equals("AUTUMN")) {
                        query = "SELECT TIME,MONDAY,TUESDAY,WEDNESDAY,THURSDAY,FRIDAY,SATURDAY FROM it5autumn";
                    } else {
                        JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "CHOOSE SEMESTER", "Warning", JOptionPane.OK_OPTION);
                }
                break;

            default:
                System.out.println("error");
                break;
        }
        
        
        try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                table.setModel(DbUtils.resultSetToTableModel(sql.resultSet));
                DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
                centerRenderer.setHorizontalAlignment( SwingConstants.CENTER );
                for(int x=0;x<=7;x++)
                table.getColumnModel().getColumn(x).setCellRenderer( centerRenderer );
                
            }
        }catch(Exception e){
            
        }
    }//GEN-LAST:event_submitButtonActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        studentstuff = new studentStuff(userName, password, logged);
        setVisible(false);
        studentstuff.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    private void clearButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMouseClicked
       ((DefaultTableModel)table.getModel()).setNumRows(0);
    }//GEN-LAST:event_clearButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentTimeTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentTimeTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel branchName;
    private javax.swing.JComboBox<String> branchSelector;
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel sectionName;
    private javax.swing.JComboBox<String> sectionSelector;
    private javax.swing.JLabel semesterName;
    private javax.swing.JComboBox<String> semesterSelector;
    private javax.swing.JButton submitButton;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
