/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.HeadlessException;
import java.sql.*;
import java.util.Arrays;
import javax.swing.JOptionPane;
/**
 *
 * @author Anant
 */

public class studentLogin extends javax.swing.JFrame {

    /**
     * Creates new form studentLogin
     */
    startLogin startlogin;
    connectionClass sql;
    String userName;
    String password;
    Boolean logged;
    
    public studentLogin() {
        initComponents();
        sql=new connectionClass();
        setSize(800, 400);
        setLocationRelativeTo(null);
    }
    
    public studentLogin(String userName, String password, Boolean logged) {
        initComponents();
        sql=new connectionClass();
        setSize(800, 400);
        setLocationRelativeTo(null);
        this.userName = userName;
        this.password = password;
        this.logged = logged;  
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        userIdfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        passwordfield = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        backButton = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        loginBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("KIIT PORTAL");
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(433, 30, 17, 332);

        jLabel1.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel1.setText("UserId");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(100, 45, 70, 21);

        userIdfield.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        userIdfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        getContentPane().add(userIdfield);
        userIdfield.setBounds(100, 78, 250, 34);

        jLabel2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel2.setText("Password");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 130, 90, 21);

        passwordfield.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 1, true));
        getContentPane().add(passwordfield);
        passwordfield.setBounds(100, 163, 250, 34);

        loginButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        loginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/login.png"))); // NOI18N
        loginButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        loginButton.setBorderPainted(false);
        loginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        getContentPane().add(loginButton);
        loginButton.setBounds(100, 230, 90, 32);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        jLabel3.setText("Forgotten password ?");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(226, 251, 98, 13);

        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/backButton.png"))); // NOI18N
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(10, 11, 16, 16);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/studentImage.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(460, 60, 312, 249);

        loginBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/AppBackground/loginbackground.png"))); // NOI18N
        getContentPane().add(loginBackground);
        loginBackground.setBounds(0, 0, 800, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
        
        String query="SELECT Userid,Password FROM StudentDetails";
        char[] passwordtext;
        passwordtext = passwordfield.getPassword();
                
                
            try{
            sql.resultSet=sql.statement.executeQuery(query);
            while(sql.resultSet.next()){
                if(userIdfield.getText().equals(sql.resultSet.getString(1))){
                    
                    if(passwordtext.equals(""))
                    {
                        JOptionPane.showMessageDialog(null, "Password cannot be empty !", "Warning", JOptionPane.OK_OPTION);
                    }
                            else if(Arrays.equals(passwordtext, sql.resultSet.getString(2).toCharArray())){
                        studentStuff student=new studentStuff(userIdfield.getText(), passwordtext.toString(),true);
                        setVisible(false);
                        student.setVisible(true);
                        sql.resultSet.close();
                        break;
                }
                    else{
                        JOptionPane.showMessageDialog(null, "Password is incorrect !", "Warning", JOptionPane.OK_OPTION);
                        userIdfield.setText("");
                        passwordfield.setText("");
                        break;
                    }
                
                    if(userIdfield.getText().equals(""))
                {
                    JOptionPane.showMessageDialog(null,"Username Cannot be Empty!","Warning",JOptionPane.OK_OPTION);
                    userIdfield.setText("");
                    passwordfield.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(null, "UserId or password is incorrect !", "Warning", JOptionPane.OK_OPTION);
                    userIdfield.setText("");
                    passwordfield.setText("");
                    }
                   }
                }
            }catch(HeadlessException | SQLException message){
            System.out.println(message);
        }
        
  
    }//GEN-LAST:event_loginButtonActionPerformed

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        startlogin = new startLogin();
        setVisible(false);
        startlogin.setVisible(true);
    }//GEN-LAST:event_backButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel loginBackground;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordfield;
    private javax.swing.JTextField userIdfield;
    // End of variables declaration//GEN-END:variables
}
